language: python
services:
    - docker
before_install:
    - docker pull evariste/autodl
    - docker run --memory=4g -it -v "$(pwd):/app/codalab" -p 8888:8888 evariste/autodl
    - docker ps -a
script:
    - python unit-testing.py
