language: python
services:
    - docker
before_install:
    - docker pull evariste/autodl
    - docker run --name autodl-container -d --memory=4g -it -v "$(pwd):/app/codalab" -p 8888:8888 evariste/autodl
script:
    - docker exec -it autodl-container python tests/unit-testing.py
    - docker exec -it autodl-container bash tests/test_parent_scoring_program.sh
    - docker exec -it autodl-container bash tests/test_baselines.sh
    - docker exec -it autodl-container bash tests/test_bad_baselines.sh
